site_name: pon.wiki
theme:
  name: material
  palette:
    primary: blue
    accent: blue
  features:
  - navigation.tracking
  - navigation.tabs
  - navigation.sections
  - navigation.expand
  - navigation.indexes
  - navigation.top
  - navigation.footer
  - announce.dismiss
  custom_dir: overrides
extra:
  generator: false
  social:
  - icon: fontawesome/brands/discord
    link: https://discord.com/servers/8311-886329492438671420
extra_css:
- stylesheets/extra.css
markdown_extensions:
- abbr
- admonition
- attr_list
- def_list
- footnotes
- md_in_html
- toc:
    permalink: true
- tables
- pymdownx.details
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format
- pymdownx.tabbed:
    alternate_style: true
nav:
- Home: index.md
- GPON:
  - gpon/index.md
  - ONU:
    - Alcatel-Lucent:
      - G-010S-P: gpon/onu/alu/g-010s-p.md
    - FS.com:
      - GPON-ONU-34-20BI: gpon/onu/fs/gpon-onu-34-20bi.md
    - Huawei:
      - MA5671A: gpon/onu/huawei/ma5671a.md
    - Nokia:
      - G-440G-A: gpon/onu/nokia/g-440g-a.md
    - ODI:
      - DFP-34X-2C2: gpon/onu/odi/dfp-34x-2c2.md
    - Source Photonics:
      - SPS-34-24T-HP-TDFO: gpon/onu/sp/sps-34-24t-hp-tdfo.md
- XGS-PON:
  - xgs-pon/index.md
  - ONU:
    - Azores Networks:
      - X1Z1E: xgs-pon/onu/azores/x1z1e.md
      - XSS: xgs-pon/onu/azores/xss.md
    - BFW:
      - WAG-D20: xgs-pon/onu/bfw/wag-d20.md
      - WAS-110: xgs-pon/onu/bfw/was-110.md
    - CIG:
      - XG-99S: xgs-pon/onu/cig/xg-99s.md
    - ECI Networks:
      - EN-XGSFPP-OMAC: xgs-pon/onu/eci/en-xgsfpp-omac.md
      - EN-XGSFPP-OMAC-V2: xgs-pon/onu/eci/en-xgsfpp-omac-v2.md
    - FS.com:
      - XGS-ONU-25-20NI: xgs-pon/onu/fs/xgs-onu-25-20ni.md
    - Fullwell Optoelectronic:
      - FWXG-890SG: xgs-pon/onu/fullwell/fwxg-890sg.md
plugins:
- search
- macros:
    include_dir: include
    include_yaml:
    - gpon_onu: include/gpon_onu.yml
    - xgs_pon_onu: include/xgs_pon_onu.yml
    - notices: include/notices.yml
    - vendors: include/vendors.yml
    on_error_fail: true
    on_undefined: strict
- glightbox
repo_url: https://github.com/up-n-atom/8311
