site_name: pon.wiki
theme:
  name: material
  palette:
    primary: blue
    accent: blue
  features:
  - navigation.tracking
  - navigation.tabs
  - navigation.sections
  - navigation.expand
  - navigation.indexes
  - navigation.top
  - navigation.footer
  - announce.dismiss
  custom_dir: overrides
extra:
  generator: false
  social:
  - icon: fontawesome/brands/discord
    link: https://discord.com/servers/8311-886329492438671420
extra_css:
- stylesheets/extra.css
markdown_extensions:
- abbr
- admonition
- attr_list
- def_list
- footnotes
- md_in_html
- toc:
    permalink: true
- tables
- pymdownx.details
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format
- pymdownx.tabbed:
    alternate_style: true
nav:
- Home: index.md
- GPON:
  - gpon/index.md
- XGS-PON:
  - xgs-pon/index.md
plugins:
- search
- macros:
    include_dir: include
    include_yaml:
    - gpon_onu: include/gpon_onu.yml
    - xgs_pon_onu: include/xgs_pon_onu.yml
    - notices: include/notices.yml
    - vendors: include/vendors.yml
    on_error_fail: true
    on_undefined: strict
- glightbox
repo_url: https://github.com/up-n-atom/8311
