site_name: pon.wiki
theme:
  name: material
  palette:
    primary: blue
    accent: blue
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - announce.dismiss
  custom_dir: overrides
extra:
  generator: false
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.com/servers/8311-886329492438671420
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - tables
  -·pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
nav:
  - Home: index.md
  - GPON:
    - gpon/index.md
  - XGS-PON:
    - xgs-pon/index.md
    - ONT:
      - BFW:
        - xgs-pon/ont/bfw/wag-d20.md
        - xgs-pon/ont/bfw/was-110i.md
      - CIG:
        - xgs-pon/ont/cig/xg-99s.md
repo_url: https://github.com/up-n-atom/8311
